#!/usr/bin/env npx tsx
/**
 * AUDIT FORGE — Monthly Audit Orchestrator
 * Cross-module + compliance + E2E + performance baseline.
 *
 * Usage: npx tsx scripts/mega-audit/monthly-audit.ts
 */

import { loadAllDomainFindings, analyzeCrossModule, generateCrossModuleReport } from './cross-module-check';
import { generateScoreDashboard, generateLifecycleSummary } from './scoring';
import { saveMonthlyReport, getLatestBaseline, detectRegressions, ensureDirectories } from './historical-tracker';
import { calculateDomainScore, calculateGlobalScore, DOMAINS, Grade } from './audit-config';
import * as fs from 'fs';
import * as path from 'path';

console.log('🔍 AUDIT FORGE — Monthly Audit');
console.log(`📅 Date: ${new Date().toISOString().slice(0, 10)}`);
console.log('');

// ── Step 1: Load all domain findings ──────────────────────────

const domainFindings = loadAllDomainFindings();
const auditedDomains = Object.keys(domainFindings);

console.log(`📊 Loaded findings from ${auditedDomains.length} domains:`);
for (const [domain, findings] of Object.entries(domainFindings)) {
  console.log(`   ${domain}: ${findings.length} findings`);
}
console.log('');

// ── Step 2: Cross-module analysis (Pass 3) ────────────────────

console.log('🔗 Running cross-module analysis...');
const crossFindings = analyzeCrossModule(domainFindings);
const crossReport = generateCrossModuleReport(crossFindings);
console.log(crossReport);
console.log('');

// ── Step 3: Domain scores ─────────────────────────────────────

const domainScores: Record<string, { score: number; grade: Grade; findingsCount: number; functionsAudited: number }> = {};
const scoreValues: Record<string, number> = {};

for (const [domain, findings] of Object.entries(domainFindings)) {
  const { score, grade } = calculateDomainScore(findings, findings.length || 1);
  domainScores[domain] = { score, grade, findingsCount: findings.length, functionsAudited: findings.length };
  scoreValues[domain] = score;
}

// ── Step 4: Global score ──────────────────────────────────────

const global = calculateGlobalScore(scoreValues);
console.log(`\n🏆 Global Platform Score: ${global.score}/100 (${global.grade})`);

// ── Step 5: Comparison with previous ──────────────────────────

const previousScores = getLatestBaseline();
const previousScoreValues: Record<string, number> | undefined = previousScores
  ? Object.fromEntries(
      Object.entries(previousScores).map(([k, v]) => [k, typeof v === 'object' ? v.score : v])
    )
  : undefined;

const dashboard = generateScoreDashboard(domainScores, previousScoreValues);
console.log('\n' + dashboard);

// ── Step 6: Regression detection ──────────────────────────────

const regressions = detectRegressions();
if (regressions.length > 0) {
  console.log('\n⚠️  REGRESSIONS DETECTED:');
  for (const r of regressions) {
    console.log(`   ${r.domain}: ${r.previousScore} → ${r.currentScore} (${r.delta})`);
  }
}

// ── Step 7: Lifecycle summary ─────────────────────────────────

const allFindings = Object.values(domainFindings).flat();
const lifecycle = generateLifecycleSummary(allFindings);
console.log('\n' + lifecycle);

// ── Step 8: Save monthly report ───────────────────────────────

ensureDirectories();
const date = new Date().toISOString().slice(0, 10);

const reportPath = saveMonthlyReport({
  date,
  domainScores: Object.fromEntries(
    Object.entries(domainScores).map(([k, v]) => [k, { score: v.score, grade: v.grade }])
  ),
  globalScore: global.score,
  globalGrade: global.grade,
  totalFindings: allFindings.length,
});

// Save full report as markdown
const reportMd = [
  `# Audit Forge — Monthly Report (${date})`,
  '',
  dashboard,
  '',
  crossReport,
  '',
  lifecycle,
  '',
  '---',
  `*Generated by Audit Forge v5.0*`,
].join('\n');

const mdPath = path.join(path.dirname(reportPath), `${date.slice(0, 7)}-monthly-report.md`);
fs.writeFileSync(mdPath, reportMd);

console.log(`\n📄 Report saved: ${reportPath}`);
console.log(`📄 Markdown: ${mdPath}`);

// ── Step 9: E2E test reminder ─────────────────────────────────

console.log('\n═══════════════════════════════════════════════════════════════');
console.log('MONTHLY CHECKLIST:');
console.log('═══════════════════════════════════════════════════════════════');
console.log('[ ] Run E2E tests: npx playwright test e2e/');
console.log('[ ] Run npm audit: npm audit --production');
console.log("[ ] Check i18n coverage: grep -r \"t('\" src/ | wc -l");
console.log('[ ] Run Semgrep: npx semgrep --config .semgrep.yml src/');
console.log('[ ] Review DASHBOARD.md for regressions');
console.log('═══════════════════════════════════════════════════════════════');
