export const dynamic = 'force-dynamic';

/**
 * Shared Cart Resolution API
 * GET /api/cart/shared/[code]
 *
 * The [code] parameter is the JWT token generated by POST /api/cart/share.
 * This endpoint decodes the token and returns items enriched with CURRENT
 * product prices and availability - not the prices at share time.
 *
 * This allows URL-based sharing: /cart?share=<token>
 * The CartShareBanner component reads the `share` query param and calls this
 * endpoint to resolve the items before offering to add them to the cart.
 */

import { NextRequest, NextResponse } from 'next/server';
import { jwtVerify } from 'jose';
import { prisma } from '@/lib/db';
import { logger } from '@/lib/logger';

// Must match the secret used in /api/cart/share
const SHARE_SECRET = new TextEncoder().encode(
  process.env.NEXTAUTH_SECRET || 'cart-share-fallback-secret-key-min-32chars!'
);

interface SharedCartItem {
  productId: string;
  formatId?: string | null;
  name: string;
  price: number;
  quantity: number;
  image?: string | null;
}

interface SharedCartPayload {
  items: SharedCartItem[];
}

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ code: string }> }
) {
  try {
    const { code } = await params;

    if (!code) {
      return NextResponse.json({ error: 'Missing share code' }, { status: 400 });
    }

    // The "code" is the JWT token - decode it
    let payload: SharedCartPayload;
    try {
      const { payload: decoded } = await jwtVerify(code, SHARE_SECRET);
      payload = (decoded as { cart: SharedCartPayload }).cart;
    } catch {
      return NextResponse.json(
        { error: 'Invalid or expired share link' },
        { status: 400 }
      );
    }

    if (!payload?.items || !Array.isArray(payload.items) || payload.items.length === 0) {
      return NextResponse.json({ error: 'No items in shared cart' }, { status: 400 });
    }

    // Collect all product IDs and format IDs we need to verify
    const productIds = [...new Set(payload.items.map((i) => i.productId))];
    const formatIds = payload.items
      .map((i) => i.formatId)
      .filter((id): id is string => !!id);

    // Fetch current product data with active formats
    const products = await prisma.product.findMany({
      where: { id: { in: productIds }, isActive: true },
      select: {
        id: true,
        name: true,
        price: true,
        imageUrl: true,
        stockQuantity: true,
        images: {
          select: { url: true },
          orderBy: { sortOrder: 'asc' },
          take: 1,
        },
        formats: {
          where: formatIds.length > 0 ? { id: { in: formatIds } } : { isActive: true },
          select: {
            id: true,
            name: true,
            price: true,
            stockQuantity: true,
            isActive: true,
          },
        },
      },
    });

    const productMap = new Map(products.map((p) => [p.id, p]));

    // Resolve items with current prices and availability
    const resolvedItems = payload.items.map((sharedItem) => {
      const product = productMap.get(sharedItem.productId);

      // Product no longer exists or is inactive
      if (!product) {
        return {
          productId: sharedItem.productId,
          formatId: sharedItem.formatId ?? null,
          name: sharedItem.name,
          quantity: sharedItem.quantity,
          currentPrice: null,
          image: sharedItem.image ?? null,
          available: false,
          unavailableReason: 'product_unavailable',
        };
      }

      // Resolve format if specified
      let currentPrice: number;
      let inStock: boolean;
      let formatName: string | undefined;

      if (sharedItem.formatId) {
        const format = product.formats.find((f) => f.id === sharedItem.formatId);
        if (!format) {
          // Format was removed - fall back to base product price
          currentPrice = Number(product.price);
          inStock = (product.stockQuantity ?? 0) > 0;
        } else {
          currentPrice = format.price ? Number(format.price) : Number(product.price);
          inStock = (format.stockQuantity ?? product.stockQuantity ?? 0) > 0;
          formatName = format.name;
        }
      } else {
        currentPrice = Number(product.price);
        inStock = (product.stockQuantity ?? 0) > 0;
      }

      // Resolve image
      const imageUrl =
        product.imageUrl ||
        (product.images.length > 0 ? product.images[0].url : null);

      return {
        productId: sharedItem.productId,
        formatId: sharedItem.formatId ?? null,
        name: product.name,
        formatName: formatName ?? null,
        quantity: sharedItem.quantity,
        currentPrice,
        image: imageUrl,
        available: inStock,
        unavailableReason: inStock ? null : 'out_of_stock',
      };
    });

    const availableCount = resolvedItems.filter((i) => i.available).length;

    return NextResponse.json({
      success: true,
      items: resolvedItems,
      itemCount: resolvedItems.reduce((sum, i) => sum + i.quantity, 0),
      availableCount,
    });
  } catch (error) {
    logger.error('Shared cart resolution failed', {
      error: error instanceof Error ? error.message : String(error),
    });
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
