/**
 * PQAP GLOSSARY — Lexique complet des 4 manuels PQAP
 * F-111 Déontologie, F-311 Assurance vie, F-312 Acc. maladie, F-313 Fonds distincts
 */

export type GlossaryCategory =
  | 'juridique' | 'assurance_personnes' | 'assurance_collective'
  | 'rentes_retraite' | 'fiscal' | 'distribution'
  | 'anti_blanchiment' | 'deontologie' | 'organismes'
  | 'invalidite_maladie' | 'fonds_distincts' | 'general';

export type GlossaryManual = 'F-111' | 'F-311' | 'F-312' | 'F-313' | 'MULTI';

export interface PqapGlossaryTerm {
  id: string;
  term: string;
  definition: string;
  category: GlossaryCategory;
  relatedTerms: string[];
  manual: GlossaryManual;
  legalReference?: string;
}

export const PQAP_GLOSSARY: PqapGlossaryTerm[] = [
  // ══════════════════════════════════════════════════
  // JURIDIQUE (~35 terms)
  // ══════════════════════════════════════════════════
  { id: 'personne-physique', term: 'Personne physique', definition: "Etre humain, titulaire de droits et d'obligations. En assurance, la personne physique peut etre preneur, assure ou beneficiaire d'un contrat.", category: 'juridique', relatedTerms: ['personne-morale', 'preneur', 'assure'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 1' },
  { id: 'personne-morale', term: 'Personne morale', definition: "Entite juridique distincte des personnes physiques qui la composent (compagnie, OBNL, cooperative). Peut detenir des polices d'assurance et etre preneur d'un contrat.", category: 'juridique', relatedTerms: ['personne-physique', 'preneur'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 298-364' },
  { id: 'patrimoine-familial', term: 'Patrimoine familial', definition: "Ensemble de biens partageables entre epoux en cas de divorce ou deces: residences, vehicules, REER, pensions. Les polices d'assurance vie avec valeur de rachat font partie du patrimoine familial.", category: 'juridique', relatedTerms: ['regime-matrimonial', 'valeur-rachat'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 414-426' },
  { id: 'regime-matrimonial', term: 'Regime matrimonial', definition: "Ensemble de regles regissant les biens des epoux: societe d'acquets (defaut au QC), separation de biens, ou communaute de biens. Affecte le partage des actifs d'assurance au deces ou divorce.", category: 'juridique', relatedTerms: ['patrimoine-familial', 'societe-acquets'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 431-492' },
  { id: 'societe-acquets', term: "Societe d'acquets", definition: "Regime matrimonial par defaut au Quebec. Les biens acquis pendant le mariage sont partageables. Les polices d'assurance vie souscrites pendant le mariage sont des acquets.", category: 'juridique', relatedTerms: ['regime-matrimonial', 'separation-biens'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 448-484' },
  { id: 'separation-biens', term: 'Separation de biens', definition: "Regime matrimonial ou chaque epoux conserve la propriete et la gestion de ses biens. Les polices d'assurance vie appartiennent au preneur qui les a souscrites.", category: 'juridique', relatedTerms: ['regime-matrimonial', 'societe-acquets'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 485-491' },
  { id: 'fiducie', term: 'Fiducie', definition: "Patrimoine autonome constitue par transfert de biens. Utilisee en planification successorale et d'assurance pour proteger des actifs, minimiser l'impot ou gerer un heritage pour des beneficiaires.", category: 'juridique', relatedTerms: ['succession', 'beneficiaire'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 1260-1298' },
  { id: 'mandat-inaptitude', term: "Mandat en cas d'inaptitude", definition: "Document juridique designant une personne pour prendre des decisions (financieres, soins) si vous devenez inapte. Important pour la gestion des polices d'assurance et des regimes de retraite.", category: 'juridique', relatedTerms: ['procuration', 'tutelle'], manual: 'F-111' },
  { id: 'succession', term: 'Succession', definition: "Transmission du patrimoine d'une personne decedee a ses heritiers. Les produits d'assurance vie avec beneficiaire designe ne font PAS partie de la succession (verses directement au beneficiaire).", category: 'juridique', relatedTerms: ['testament', 'beneficiaire-designe', 'fiducie'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 613+' },
  { id: 'testament', term: 'Testament', definition: "Acte juridique par lequel une personne dispose de ses biens pour apres son deces. Peut contenir une designation de beneficiaire d'assurance vie, mais celle-ci est generalement faite dans le contrat.", category: 'juridique', relatedTerms: ['succession', 'beneficiaire-designe'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 704-775' },
  { id: 'subrogation', term: 'Subrogation', definition: "Mecanisme juridique par lequel l'assureur, apres avoir indemnise l'assure, acquiert le droit de poursuivre le tiers responsable du dommage. S'applique principalement en assurance de dommages.", category: 'juridique', relatedTerms: ['indemnite', 'responsabilite-civile'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 2474' },
  { id: 'insaisissabilite', term: 'Insaisissabilite', definition: "Protection legale empechant les creanciers de saisir certains biens. Au Quebec, les prestations d'assurance vie avec beneficiaire designe sont insaisissables par les creanciers du preneur.", category: 'juridique', relatedTerms: ['beneficiaire-designe', 'fonds-distincts-terme'], manual: 'F-311', legalReference: 'Code civil du Quebec, art. 2457-2458' },
  { id: 'bonne-foi', term: 'Bonne foi (uberrimae fidei)', definition: "Principe fondamental du contrat d'assurance: obligation de la plus haute bonne foi pour les deux parties. L'assure doit declarer tous les faits pertinents; l'assureur doit informer clairement.", category: 'juridique', relatedTerms: ['declaration-assure', 'divulgation'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 2408' },
  { id: 'prescription', term: 'Prescription', definition: "Delai legal au-dela duquel un droit ne peut plus etre exerce. En assurance au QC, la prescription est de 3 ans a compter de la connaissance du sinistre.", category: 'juridique', relatedTerms: ['sinistre', 'reclamation'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 2925' },
  { id: 'responsabilite-civile', term: 'Responsabilite civile', definition: "Obligation legale de reparer les dommages causes a autrui par sa faute. L'assurance RC couvre les frais de defense et indemnites. Fondement du regime de responsabilite au Quebec.", category: 'juridique', relatedTerms: ['subrogation', 'dommages-materiels'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 1457-1481' },
  { id: 'contrat-adhesion', term: "Contrat d'adhesion", definition: "Contrat dont les clauses essentielles sont imposees par une partie sans possibilite de negociation. Les polices d'assurance sont des contrats d'adhesion, ce qui justifie l'interpretation en faveur de l'assure.", category: 'juridique', relatedTerms: ['police', 'contra-proferentem'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 1379' },
  { id: 'stipulation-pour-autrui', term: 'Stipulation pour autrui', definition: "Clause par laquelle le preneur d'assurance designe un beneficiaire (tiers) qui acquiert un droit direct contre l'assureur. Fondement juridique de la designation de beneficiaire.", category: 'juridique', relatedTerms: ['beneficiaire-designe', 'preneur'], manual: 'F-111', legalReference: 'Code civil du Quebec, art. 1444-1450' },

  // ══════════════════════════════════════════════════
  // ASSURANCE DE PERSONNES (~40 terms)
  // ══════════════════════════════════════════════════
  { id: 'preneur', term: 'Preneur', definition: "Personne qui conclut le contrat d'assurance et s'engage a payer les primes. Peut etre different de l'assure et du beneficiaire. Aussi appele titulaire ou contractant.", category: 'assurance_personnes', relatedTerms: ['assure', 'beneficiaire-designe', 'police'], manual: 'F-311' },
  { id: 'assure', term: 'Assure', definition: "Personne dont la vie ou la sante est couverte par le contrat d'assurance. Son deces ou son invalidite declenche le versement des prestations au beneficiaire.", category: 'assurance_personnes', relatedTerms: ['preneur', 'beneficiaire-designe'], manual: 'F-311' },
  { id: 'beneficiaire-designe', term: 'Beneficiaire designe', definition: "Personne nommee dans le contrat pour recevoir les prestations. Peut etre revocable (modifiable par le preneur) ou irrevocable (necessite le consentement du beneficiaire pour changer).", category: 'assurance_personnes', relatedTerms: ['beneficiaire-irrevocable', 'preneur', 'insaisissabilite'], manual: 'F-311', legalReference: 'Code civil du Quebec, art. 2445-2460' },
  { id: 'beneficiaire-irrevocable', term: 'Beneficiaire irrevocable', definition: "Beneficiaire dont la designation ne peut etre modifiee sans son consentement ecrit. Le preneur perd le controle sur la police. La designation du conjoint marie est irrevocable par defaut au QC.", category: 'assurance_personnes', relatedTerms: ['beneficiaire-designe', 'preneur'], manual: 'F-311', legalReference: 'Code civil du Quebec, art. 2449' },
  { id: 'police', term: "Police d'assurance", definition: "Document ecrit constatant le contrat d'assurance. Contient les conditions, couvertures, exclusions et obligations. C'est le contrat de reference en cas de reclamation.", category: 'assurance_personnes', relatedTerms: ['avenant', 'exclusion', 'prime'], manual: 'MULTI', legalReference: 'Code civil du Quebec, art. 2399-2414' },
  { id: 'prime', term: 'Prime', definition: "Somme payee par le preneur a l'assureur pour obtenir et maintenir la couverture. Calculee selon le risque, l'age, la sante, le montant assure et le type de produit.", category: 'assurance_personnes', relatedTerms: ['tarification', 'surprime', 'franchise'], manual: 'MULTI' },
  { id: 'capital-deces', term: 'Capital deces', definition: "Montant verse au beneficiaire lors du deces de l'assure. Generalement libre d'impot. Peut etre un montant fixe ou variable selon le type de police.", category: 'assurance_personnes', relatedTerms: ['beneficiaire-designe', 'assurance-temporaire'], manual: 'F-311' },
  { id: 'valeur-rachat', term: 'Valeur de rachat', definition: "Somme accumulee dans une police permanente que le preneur peut recuperer en mettant fin au contrat. Presente dans les polices vie entiere et universelle. Le rachat peut avoir des consequences fiscales.", category: 'assurance_personnes', relatedTerms: ['assurance-vie-entiere', 'assurance-universelle', 'gain-sur-police'], manual: 'F-311' },
  { id: 'assurance-temporaire', term: 'Assurance temporaire', definition: "Assurance vie couvrant une periode definie (T10, T20, T30 ou TAR). Pas de valeur de rachat. Prime initialement basse mais augmente au renouvellement. Ideale pour besoins temporaires.", category: 'assurance_personnes', relatedTerms: ['assurance-vie-entiere', 'capital-deces', 'droit-transformation'], manual: 'F-311' },
  { id: 'assurance-vie-entiere', term: 'Assurance vie entiere', definition: "Assurance permanente garantie a vie avec primes fixes nivelees. Accumule une valeur de rachat. Peut etre participante (dividendes) ou non. La couverture reste en vigueur tant que les primes sont payees.", category: 'assurance_personnes', relatedTerms: ['assurance-temporaire', 'assurance-universelle', 'valeur-rachat'], manual: 'F-311' },
  { id: 'assurance-universelle', term: 'Assurance universelle', definition: "Assurance permanente combinant protection et epargne flexible. Le preneur choisit le montant des primes (entre un minimum et maximum) et le type de placement. Produit complexe necessitant un devoir de conseil rigoureux.", category: 'assurance_personnes', relatedTerms: ['assurance-vie-entiere', 'valeur-rachat'], manual: 'F-311' },
  { id: 'assurance-participante', term: 'Assurance vie avec participation', definition: "Police vie entiere dont les detenteurs participent aux profits de l'assureur via des dividendes (participations). Options: reduction primes, achat couverture additionnelle, accumulation avec interets, encaissement.", category: 'assurance_personnes', relatedTerms: ['assurance-vie-entiere', 'dividendes-police'], manual: 'F-311' },
  { id: 'assurance-dernier-deces', term: 'Assurance dernier deces', definition: "Police couvrant deux vies qui verse le capital deces au deces du DERNIER survivant. Utilisee en planification successorale pour payer l'impot au deces du deuxieme conjoint.", category: 'assurance_personnes', relatedTerms: ['assurance-conjointe-premier-deces', 'succession'], manual: 'F-311' },
  { id: 'assurance-conjointe-premier-deces', term: 'Assurance conjointe premier deces', definition: "Police couvrant deux vies qui verse le capital au deces du PREMIER des deux assures. Plus economique que deux polices individuelles. Le survivant perd alors sa couverture.", category: 'assurance_personnes', relatedTerms: ['assurance-dernier-deces'], manual: 'F-311' },
  { id: 'droit-transformation', term: 'Droit de transformation', definition: "Privilege permettant de convertir une assurance temporaire en assurance permanente sans preuve d'assurabilite. Doit etre exerce avant l'age limite prevu au contrat.", category: 'assurance_personnes', relatedTerms: ['assurance-temporaire', 'assurance-vie-entiere'], manual: 'F-311' },
  { id: 'periode-contestabilite', term: "Periode de contestabilite", definition: "Delai de 2 ans pendant lequel l'assureur peut annuler un contrat pour fausse declaration ou omission. Apres 2 ans, le contrat devient incontestable sauf en cas de fraude.", category: 'assurance_personnes', relatedTerms: ['declaration-assure', 'incontestabilite'], manual: 'F-311', legalReference: 'Code civil du Quebec, art. 2424' },
  { id: 'incontestabilite', term: 'Incontestabilite', definition: "Apres la periode de contestabilite (2 ans), l'assureur ne peut plus annuler le contrat meme si des fausses declarations sont decouvertes, sauf en cas de fraude.", category: 'assurance_personnes', relatedTerms: ['periode-contestabilite', 'declaration-assure'], manual: 'F-311', legalReference: 'Code civil du Quebec, art. 2424' },
  { id: 'declaration-assure', term: "Declaration de l'assure", definition: "Informations fournies par le proposant sur sa sante, mode de vie, profession et antecedents. Base de l'evaluation du risque. Doit etre complete et veridique sous peine de nullite.", category: 'assurance_personnes', relatedTerms: ['bonne-foi', 'periode-contestabilite', 'tarification'], manual: 'F-311', legalReference: 'Code civil du Quebec, art. 2408-2413' },
  { id: 'avenant', term: 'Avenant', definition: "Document modifiant les conditions d'un contrat d'assurance en vigueur. Ajoute, modifie ou supprime des garanties. Fait partie integrante de la police. Ex: avenant exoneration des primes.", category: 'assurance_personnes', relatedTerms: ['police', 'exclusion'], manual: 'MULTI', legalReference: 'Code civil du Quebec, art. 2405' },
  { id: 'exclusion', term: 'Exclusion', definition: "Situation specifiquement non couverte par le contrat. Exclusions courantes: suicide (2 ans), acte criminel, guerre, aviation non commerciale. Le representant doit expliquer toutes les exclusions.", category: 'assurance_personnes', relatedTerms: ['police', 'avenant', 'clause-suicide'], manual: 'MULTI' },
  { id: 'clause-suicide', term: 'Clause de suicide', definition: "Exclusion prevoyant que l'assureur ne paie pas le capital deces si l'assure se suicide dans les 2 premieres annees du contrat. Apres 2 ans, le suicide est couvert.", category: 'assurance_personnes', relatedTerms: ['exclusion', 'periode-contestabilite'], manual: 'F-311', legalReference: 'Code civil du Quebec, art. 2441' },
  { id: 'surprime', term: 'Surprime', definition: "Montant supplementaire ajoute a la prime standard en raison d'un risque aggrave (sante, profession, loisirs dangereux). Permet d'assurer des personnes qui seraient autrement refusees.", category: 'assurance_personnes', relatedTerms: ['tarification', 'prime'], manual: 'F-311' },
  { id: 'tarification', term: 'Tarification (souscription)', definition: "Processus d'evaluation du risque par l'assureur pour determiner la prime. Analyse: age, sexe, sante, antecedents familiaux, profession, loisirs, tabagisme. Classes: standard, preferee, a risque.", category: 'assurance_personnes', relatedTerms: ['prime', 'surprime', 'declaration-assure'], manual: 'F-311' },
  { id: 'pret-sur-police', term: 'Pret sur police', definition: "Emprunt garanti par la valeur de rachat d'une police permanente. L'assure emprunte a l'assureur sans devoir rembourser de son vivant. Le solde du pret est deduit du capital deces.", category: 'assurance_personnes', relatedTerms: ['valeur-rachat', 'assurance-vie-entiere'], manual: 'F-311' },
  { id: 'remise-en-vigueur', term: 'Remise en vigueur', definition: "Reactivation d'une police tombee en decheance pour non-paiement des primes. Necessite generalement une preuve d'assurabilite et le paiement des primes arriérees. Delai habituel: 2 ans.", category: 'assurance_personnes', relatedTerms: ['prime', 'police'], manual: 'F-311' },
  { id: 'option-reglement', term: "Options de reglement", definition: "Modes de versement du capital deces au beneficiaire: montant forfaitaire, rente viagere, rente certaine, versements echelonnes, depot avec interets. Le beneficiaire choisit generalement.", category: 'assurance_personnes', relatedTerms: ['capital-deces', 'beneficiaire-designe', 'rente-viagere'], manual: 'F-311' },
  { id: 'assurance-hypothecaire', term: 'Assurance hypothecaire', definition: "Assurance vie temporaire decroissante couvrant le solde du pret hypothecaire. Le beneficiaire est le preteur. Alternative: assurance vie individuelle avec beneficiaire au choix (plus flexible).", category: 'assurance_personnes', relatedTerms: ['assurance-temporaire', 'assurance-credit'], manual: 'F-311' },

  // ══════════════════════════════════════════════════
  // ASSURANCE COLLECTIVE (~15 terms)
  // ══════════════════════════════════════════════════
  { id: 'adherent', term: 'Adherent', definition: "Personne couverte par un regime d'assurance collective. Recoit un certificat d'assurance (pas la police). Ses droits sont determines par le contrat-cadre entre l'employeur et l'assureur.", category: 'assurance_collective', relatedTerms: ['contrat-cadre', 'certificat-assurance'], manual: 'F-312' },
  { id: 'contrat-cadre', term: 'Contrat-cadre', definition: "Police d'assurance collective detenue par le preneur de groupe (employeur, association). Definit les garanties, conditions et modalites pour tous les adherents.", category: 'assurance_collective', relatedTerms: ['adherent', 'certificat-assurance'], manual: 'F-312' },
  { id: 'certificat-assurance', term: "Certificat d'assurance", definition: "Document individuel remis a chaque adherent d'un regime collectif. Resume les protections, montants, conditions et exclusions applicables. N'est pas la police elle-meme.", category: 'assurance_collective', relatedTerms: ['contrat-cadre', 'adherent'], manual: 'F-312' },
  { id: 'regime-contributif', term: 'Regime contributif', definition: "Regime collectif ou les adherents paient une partie des primes (l'employeur paie le reste). Les prestations versees sont alors generalement non imposables pour l'adherent.", category: 'assurance_collective', relatedTerms: ['regime-non-contributif', 'contrat-cadre'], manual: 'F-312' },
  { id: 'regime-non-contributif', term: 'Regime non contributif', definition: "Regime collectif ou l'employeur paie la totalite des primes. Les prestations d'invalidite sont alors imposables pour l'adherent car la prime est un avantage imposable.", category: 'assurance_collective', relatedTerms: ['regime-contributif', 'avantage-imposable'], manual: 'F-312' },
  { id: 'droit-transformation-collective', term: 'Droit de transformation (collectif)', definition: "Droit pour l'adherent quittant un regime collectif de convertir sa couverture en police individuelle sans preuve d'assurabilite. Doit etre exerce dans les 31 jours suivant la fin de la couverture.", category: 'assurance_collective', relatedTerms: ['adherent', 'droit-transformation'], manual: 'F-312' },
  { id: 'clause-coordination', term: 'Clause de coordination', definition: "Clause determinant l'ordre de paiement quand un adherent est couvert par deux regimes. Le regime principal (de l'employe) paie en premier, le second regime couvre la difference.", category: 'assurance_collective', relatedTerms: ['contrat-cadre', 'adherent'], manual: 'F-312' },
  { id: 'periode-attente', term: "Periode d'attente (delai de carence)", definition: "Delai avant qu'un nouvel adherent soit couvert par le regime collectif (souvent 3 mois). Aussi le delai avant le debut des prestations d'invalidite (30, 60 ou 90 jours).", category: 'assurance_collective', relatedTerms: ['adherent', 'invalidite-longue-duree'], manual: 'F-312' },
  { id: 'aso', term: 'ASO (Administrative Services Only)', definition: "Regime non assure ou l'employeur assume le risque financier et l'assureur ne fournit que les services administratifs (traitement des reclamations). Utilise par les grandes entreprises.", category: 'assurance_collective', relatedTerms: ['contrat-cadre', 'regime-non-contributif'], manual: 'F-312' },

  // ══════════════════════════════════════════════════
  // RENTES ET RETRAITE (~25 terms)
  // ══════════════════════════════════════════════════
  { id: 'reer', term: 'REER', definition: "Regime enregistre d'epargne-retraite. Cotisations deductibles du revenu imposable (18% du revenu gagne, max annuel). Croissance a l'abri de l'impot. Retraits imposables. Conversion en FERR a 71 ans.", category: 'rentes_retraite', relatedTerms: ['ferr', 'celi', 'rpa'], manual: 'F-313', legalReference: 'Loi de l\'impot sur le revenu, art. 146' },
  { id: 'ferr', term: 'FERR', definition: "Fonds enregistre de revenu de retraite. Vehicule de decaissement du REER apres 71 ans. Retrait minimum obligatoire chaque annee. Retraits imposables. Pas de maximum.", category: 'rentes_retraite', relatedTerms: ['reer', 'cri', 'frv'], manual: 'F-313', legalReference: 'Loi de l\'impot sur le revenu, art. 146.3' },
  { id: 'cri', term: 'CRI', definition: "Compte de retraite immobilise. Recoit les fonds d'un regime de retraite a la cessation d'emploi. Fonds immobilises (non retirables sauf exceptions). Converti en FRV a la retraite.", category: 'rentes_retraite', relatedTerms: ['frv', 'rpa', 'ferr'], manual: 'F-313', legalReference: 'Loi sur les regimes complementaires de retraite, RLRQ c. R-15.1' },
  { id: 'frv', term: 'FRV', definition: "Fonds de revenu viager. Vehicule de decaissement des fonds immobilises (CRI). Impose retrait minimum ET maximum annuel. A 65 ans, possibilite de transferer 40% dans un FERR non immobilise.", category: 'rentes_retraite', relatedTerms: ['cri', 'ferr', 'reer'], manual: 'F-313', legalReference: 'Loi sur les regimes complementaires de retraite, RLRQ c. R-15.1' },
  { id: 'celi', term: 'CELI', definition: "Compte d'epargne libre d'impot. Cotisations non deductibles, mais croissance et retraits libres d'impot. Plafond cumulatif depuis 2009. Excellent complement au REER.", category: 'rentes_retraite', relatedTerms: ['reer', 'celiapp'], manual: 'F-313' },
  { id: 'celiapp', term: 'CELIAPP', definition: "Compte d'epargne libre d'impot pour l'achat d'une premiere propriete. Cotisations deductibles (comme REER), retraits non imposables si pour achat maison. Max 8000$/an, 40000$ a vie.", category: 'rentes_retraite', relatedTerms: ['celi', 'reer'], manual: 'F-313' },
  { id: 'rver', term: 'RVER', definition: "Regime volontaire d'epargne-retraite. Regime collectif simplifie que les employeurs de 5+ employes sans regime de retraite doivent offrir. Adhesion automatique, option de retrait.", category: 'rentes_retraite', relatedTerms: ['reer', 'rpa'], manual: 'F-313', legalReference: 'Loi sur les RVER, RLRQ c. R-17.0.1' },
  { id: 'reee', term: 'REEE', definition: "Regime enregistre d'epargne-etudes. Cotisations non deductibles. Subventions gouvernementales (SCEE 20%, IQEE 10% QC). Rendement a l'abri de l'impot. Retraits (PAE) imposables pour l'etudiant.", category: 'rentes_retraite', relatedTerms: ['reer', 'reei'], manual: 'F-313' },
  { id: 'reei', term: 'REEI', definition: "Regime enregistre d'epargne-invalidite. Pour personnes admissibles au credit d'impot pour handicap. Subventions (SCEI) et bons (BCEI) gouvernementaux. Maximum 200 000$ a vie.", category: 'rentes_retraite', relatedTerms: ['reee', 'invalidite-totale'], manual: 'F-313' },
  { id: 'rpa', term: 'RPA', definition: "Regime de pension agree (regime de retraite d'employeur). Peut etre a prestations determinees (PD: rente garantie) ou a cotisations determinees (CD: valeur variable). Fonds immobilises.", category: 'rentes_retraite', relatedTerms: ['cri', 'frv', 'rver'], manual: 'F-313' },
  { id: 'rente-viagere', term: 'Rente viagere', definition: "Serie de versements periodiques garantis jusqu'au deces du rentier. Peut etre avec periode garantie (ex: 10 ans certaine + viagere). Utilisee pour convertir un capital en revenu a vie.", category: 'rentes_retraite', relatedTerms: ['rente-certaine', 'rente-prescrite'], manual: 'F-313' },
  { id: 'rente-certaine', term: 'Rente certaine', definition: "Rente versee pour une periode fixe (ex: 10, 15, 20 ans) independamment du deces du rentier. Si le rentier decede, les versements continuent aux beneficiaires jusqu'a la fin de la periode.", category: 'rentes_retraite', relatedTerms: ['rente-viagere', 'option-reglement'], manual: 'F-313' },
  { id: 'rente-prescrite', term: 'Rente prescrite', definition: "Rente dont la portion imposable est repartie egalement sur la duree prevue des versements. Avantageuse fiscalement car le revenu imposable est constant, contrairement a la rente non prescrite.", category: 'rentes_retraite', relatedTerms: ['rente-non-prescrite', 'rente-viagere'], manual: 'F-313' },
  { id: 'rente-non-prescrite', term: 'Rente non prescrite', definition: "Rente dont la portion imposable est plus elevee au debut et diminue avec le temps (car le capital diminue). Desavantageuse fiscalement car les premieres annees ont le revenu imposable le plus eleve.", category: 'rentes_retraite', relatedTerms: ['rente-prescrite', 'rente-viagere'], manual: 'F-313' },
  { id: 'cig', term: 'CIG (Contrat individuel garanti)', definition: "Placement a terme offert par un assureur, semblable au CPG bancaire. Taux garanti pour une duree fixe. Eligible REER/FERR/CELI. Garanti par l'assureur (pas SADC mais Assuris).", category: 'rentes_retraite', relatedTerms: ['fonds-distincts-terme', 'assuris-org'], manual: 'F-313' },

  // ══════════════════════════════════════════════════
  // FISCAL (~20 terms)
  // ══════════════════════════════════════════════════
  { id: 'cbr', term: 'CBR (Cout de base rajuste)', definition: "Cout fiscal d'une police d'assurance vie. Represente le total des primes nettes de cout d'assurance versees. Sert a calculer le gain imposable lors d'une disposition ou d'un rachat.", category: 'fiscal', relatedTerms: ['gain-sur-police', 'police-exoneree'], manual: 'F-311' },
  { id: 'gain-sur-police', term: 'Gain sur police', definition: "Montant imposable lors du rachat ou de la disposition d'une police. Calcul: valeur de rachat - CBR. Si positif, imposable comme revenu ordinaire (pas gain en capital).", category: 'fiscal', relatedTerms: ['cbr', 'valeur-rachat', 'police-exoneree'], manual: 'F-311' },
  { id: 'police-exoneree', term: 'Police exoneree', definition: "Police d'assurance vie dont l'epargne croit a l'abri de l'impot tant qu'elle n'est pas rachetee. Doit respecter le test d'exemption (limite d'accumulation). La plupart des polices vie entiere sont exonerees.", category: 'fiscal', relatedTerms: ['police-non-exoneree', 'cbr', 'test-exemption'], manual: 'F-311' },
  { id: 'police-non-exoneree', term: 'Police non exoneree', definition: "Police dont l'epargne excede le test d'exemption. Le revenu de placement est imposable annuellement meme sans retrait (revenu couru). Generalement, les polices avec depot excessif.", category: 'fiscal', relatedTerms: ['police-exoneree', 'test-exemption'], manual: 'F-311' },
  { id: 'test-exemption', term: "Test d'exemption (PTE/RAMI)", definition: "Test fiscal determinant si une police est exoneree ou non. Compare l'accumulation dans la police a une police de reference (assurance vie entiere nivelée). Regle des 250% abolie et remplacee.", category: 'fiscal', relatedTerms: ['police-exoneree', 'police-non-exoneree'], manual: 'F-311' },
  { id: 'cdc', term: 'CDC (Compte de dividendes en capital)', definition: "Compte notionnel d'une societe privee. Recoit la portion non imposable du capital deces d'une police d'assurance detenue par la societe. Permet de verser des dividendes en capital libres d'impot aux actionnaires.", category: 'fiscal', relatedTerms: ['assurance-personne-cle', 'convention-actionnaires'], manual: 'F-311' },
  { id: 'disposition-presumee', term: 'Disposition presumee', definition: "Evenement fiscal traite comme une vente meme sans transaction reelle. En assurance, le transfert d'une police, le changement de beneficiaire ou le deces du preneur peut declencher une disposition presumee.", category: 'fiscal', relatedTerms: ['gain-sur-police', 'roulement-conjoint'], manual: 'F-311' },
  { id: 'roulement-conjoint', term: 'Roulement au conjoint', definition: "Transfert d'une police d'assurance vie au conjoint sans consequences fiscales immediates (report de l'impot). Le CBR est transfere au conjoint. Disponible entre vifs ou au deces.", category: 'fiscal', relatedTerms: ['disposition-presumee', 'cbr'], manual: 'F-311' },
  { id: 'avantage-imposable', term: 'Avantage imposable', definition: "Valeur de la prime d'assurance collective payee par l'employeur. Constitue un revenu imposable pour l'employe. Cependant, si l'employe paie sa part de prime, les prestations ne sont pas imposables.", category: 'fiscal', relatedTerms: ['regime-contributif', 'regime-non-contributif'], manual: 'F-312' },
  { id: 'assurance-personne-cle', term: 'Assurance personne cle', definition: "Assurance vie sur la tete d'un employe essentiel, detenue et payee par l'entreprise. Le capital deces indemnise l'entreprise pour la perte. Prime non deductible. Capital deces credit au CDC.", category: 'fiscal', relatedTerms: ['cdc', 'convention-actionnaires'], manual: 'F-311' },
  { id: 'convention-actionnaires', term: 'Convention entre actionnaires', definition: "Entente prevoyant le rachat des actions d'un actionnaire au deces ou invalidite, souvent financee par l'assurance vie. Types: rachat croise (actionnaires) ou rachat par la societe.", category: 'fiscal', relatedTerms: ['assurance-personne-cle', 'cdc'], manual: 'F-311' },

  // ══════════════════════════════════════════════════
  // DISTRIBUTION (~15 terms)
  // ══════════════════════════════════════════════════
  { id: 'representant', term: 'Representant', definition: "Personne certifiee par l'AMF pour offrir des produits d'assurance. Peut etre agent (lie a un assureur) ou courtier (independant). Soumis au devoir de conseil, formation continue et deontologie.", category: 'distribution', relatedTerms: ['cabinet', 'courtier-terme', 'agent-terme'], manual: 'F-111', legalReference: 'LDPSF, art. 12-20' },
  { id: 'cabinet', term: 'Cabinet', definition: "Entreprise autorisee a distribuer des produits d'assurance. Emploie ou est rattache a des representants. Peut etre exclusif (un assureur) ou independant (plusieurs). Responsable de la supervision.", category: 'distribution', relatedTerms: ['representant', 'societe-autonome'], manual: 'F-111', legalReference: 'LDPSF, art. 71-78' },
  { id: 'devoir-conseil', term: 'Devoir de conseil', definition: "Obligation fondamentale du representant: comprendre les besoins du client, recommander les produits adaptes, expliquer avantages et inconvenients, documenter le tout. Manquement = sanctions disciplinaires.", category: 'distribution', relatedTerms: ['analyse-besoins', 'kyc', 'convenance-produit'], manual: 'F-111', legalReference: 'LDPSF, art. 27-28' },
  { id: 'analyse-besoins', term: 'Analyse des besoins (ABF)', definition: "Processus obligatoire d'evaluation de la situation financiere, familiale et des objectifs du client avant toute recommandation. Doit etre documentee dans le dossier client.", category: 'distribution', relatedTerms: ['devoir-conseil', 'kyc'], manual: 'F-111', legalReference: 'LDPSF, art. 27, al. 1' },
  { id: 'kyc', term: 'KYC (Connaissance du client)', definition: "Obligation de connaitre l'identite, la situation financiere, les objectifs et la tolerance au risque du client. Inclut la verification d'identite (anti-blanchiment) et l'analyse des besoins.", category: 'distribution', relatedTerms: ['analyse-besoins', 'devoir-conseil', 'coi'], manual: 'F-111' },
  { id: 'convenance-produit', term: 'Convenance du produit', definition: "Obligation de s'assurer que le produit recommande est convenable pour le client en fonction de ses besoins, sa situation financiere et sa tolerance au risque. Concept central du devoir de conseil.", category: 'distribution', relatedTerms: ['devoir-conseil', 'analyse-besoins'], manual: 'F-111' },
  { id: 'dsr', term: 'DSR (Frais de rachat differes)', definition: "Commission versee au representant par l'assureur a la vente. Si le client rachete la police dans les premieres annees (5-7 ans), des frais de rachat s'appliquent. Aussi appele back-end load.", category: 'distribution', relatedTerms: ['commission', 'fonds-distincts-terme'], manual: 'F-313' },
  { id: 'registre-plaintes', term: 'Registre des plaintes', definition: "Registre que chaque cabinet doit tenir pour consigner toutes les plaintes recues. Doit etre accessible a l'AMF. Fait partie des obligations de conformite du cabinet.", category: 'distribution', relatedTerms: ['cabinet', 'syndic'], manual: 'F-111' },

  // ══════════════════════════════════════════════════
  // DEONTOLOGIE (~15 terms)
  // ══════════════════════════════════════════════════
  { id: 'probite', term: 'Probite', definition: "Qualite d'honnetete et de droiture exigee du representant. Interdiction d'induire en erreur, de faire de fausses representations ou d'utiliser des pratiques deloyales.", category: 'deontologie', relatedTerms: ['diligence', 'loyaute'], manual: 'F-111', legalReference: 'CDCSF, art. 2-3' },
  { id: 'diligence', term: 'Diligence', definition: "Obligation d'agir avec soin, attention et competence dans l'exercice de ses fonctions. Le representant doit effectuer un suivi regulier des dossiers clients et mettre a jour les polices.", category: 'deontologie', relatedTerms: ['probite', 'loyaute', 'competence'], manual: 'F-111', legalReference: 'CDCSF, art. 4' },
  { id: 'loyaute', term: 'Loyaute', definition: "Obligation de toujours agir dans le meilleur interet du client, meme si cela va a l'encontre des interets du representant ou du cabinet. Priorite absolue: le client.", category: 'deontologie', relatedTerms: ['probite', 'conflit-interets'], manual: 'F-111', legalReference: 'CDCSF, art. 5' },
  { id: 'conflit-interets', term: "Conflit d'interets", definition: "Situation ou les interets personnels du representant pourraient influencer ses recommandations au client. Doit etre declare par ecrit. Exemples: commissions, liens avec assureur, interets financiers.", category: 'deontologie', relatedTerms: ['loyaute', 'divulgation'], manual: 'F-111', legalReference: 'LDPSF, art. 18-19' },
  { id: 'secret-professionnel', term: 'Secret professionnel', definition: "Obligation de confidentialite sur toute information obtenue dans l'exercice de ses fonctions. Le representant ne peut divulguer d'informations sur un client sans son consentement, sauf exceptions legales.", category: 'deontologie', relatedTerms: ['conflit-interets', 'loi-25'], manual: 'F-111', legalReference: 'CDCSF, art. 26' },
  { id: 'syndic', term: 'Syndic', definition: "Fonctionnaire de la CSF charge d'enqueter sur les plaintes contre les representants. Peut deposer une plainte disciplinaire devant le comite de discipline si une infraction est constatee.", category: 'deontologie', relatedTerms: ['comite-discipline', 'sanctions-disciplinaires'], manual: 'F-111' },
  { id: 'comite-discipline', term: 'Comite de discipline', definition: "Tribunal disciplinaire de la CSF qui entend les plaintes contre les representants. Peut imposer des sanctions: reprimande, amende, suspension, radiation, formation obligatoire.", category: 'deontologie', relatedTerms: ['syndic', 'sanctions-disciplinaires'], manual: 'F-111' },
  { id: 'sanctions-disciplinaires', term: 'Sanctions disciplinaires', definition: "Penalites imposees par le comite de discipline: reprimande, amende (max fixe par reglement), suspension temporaire, radiation permanente, obligation de formation corrective, remboursement des frais.", category: 'deontologie', relatedTerms: ['comite-discipline', 'syndic'], manual: 'F-111' },

  // ══════════════════════════════════════════════════
  // ANTI-BLANCHIMENT (~12 terms)
  // ══════════════════════════════════════════════════
  { id: 'ppv', term: 'PPV (Personne politiquement vulnerable)', definition: "Terme general couvrant les PEP, EPV et NPV. Personnes occupant ou ayant occupe des fonctions politiques importantes. Necessitent une surveillance accrue des transactions.", category: 'anti_blanchiment', relatedTerms: ['epv', 'npv', 'canafe'], manual: 'F-313' },
  { id: 'epv', term: 'EPV (Etranger politiquement vulnerable)', definition: "Ressortissant etranger occupant une fonction politique importante (chef d'Etat, ministre, juge supreme, ambassadeur). Client a risque eleve necessitant des mesures de surveillance renforcees.", category: 'anti_blanchiment', relatedTerms: ['ppv', 'npv', 'canafe'], manual: 'F-313' },
  { id: 'npv', term: 'NPV (National politiquement vulnerable)', definition: "Citoyen canadien occupant une fonction politique importante. Necessite une determination de risque mais pas automatiquement un client a risque eleve (contrairement aux EPV).", category: 'anti_blanchiment', relatedTerms: ['ppv', 'epv'], manual: 'F-313' },
  { id: 'beneficiaire-effectif', term: 'Beneficiaire effectif', definition: "Personne physique qui possede ou controle ultimement un client entite (societe). Doit etre identifie pour les transactions de 10 000$+. Obligation FINTRAC pour prevenir le blanchiment.", category: 'anti_blanchiment', relatedTerms: ['coi', 'canafe'], manual: 'F-313' },
  { id: 'dod', term: 'DOD (Declaration d\'operation douteuse)', definition: "Rapport obligatoire a CANAFE quand le representant a des motifs raisonnables de soupconner une operation liee au blanchiment ou au financement terroriste. Pas de seuil monetaire.", category: 'anti_blanchiment', relatedTerms: ['canafe', 'programme-conformite-aml'], manual: 'F-313', legalReference: 'LRPCFAT, art. 7' },
  { id: 'coi', term: 'COI (Confirmation d\'identite)', definition: "Processus de verification de l'identite du client au moyen de documents officiels (permis, passeport) ou de methodes alternatives (bureau de credit, correspondance). Obligatoire pour FINTRAC.", category: 'anti_blanchiment', relatedTerms: ['kyc', 'beneficiaire-effectif'], manual: 'F-313' },
  { id: 'canafe', term: 'CANAFE / FINTRAC', definition: "Centre d'analyse des operations et declarations financieres du Canada. Organisme federal de renseignement financier. Recoit les declarations d'operations douteuses et les rapports de grandes operations.", category: 'anti_blanchiment', relatedTerms: ['dod', 'programme-conformite-aml', 'lrpcfat'], manual: 'F-313' },
  { id: 'lrpcfat', term: 'LRPCFAT / PCMLTFA', definition: "Loi sur le recyclage des produits de la criminalite et le financement des activites terroristes. Loi federale imposant des obligations anti-blanchiment a tous les intermediaires financiers dont les representants.", category: 'anti_blanchiment', relatedTerms: ['canafe', 'dod'], manual: 'F-313' },
  { id: 'programme-conformite-aml', term: 'Programme de conformite (AML)', definition: "Programme obligatoire que chaque entite declarante doit maintenir: agent de conformite designe, politiques ecrites, formation du personnel, evaluation des risques, examen d'efficacite tous les 2 ans.", category: 'anti_blanchiment', relatedTerms: ['canafe', 'lrpcfat'], manual: 'F-313' },

  // ══════════════════════════════════════════════════
  // INVALIDITE ET MALADIE (~12 terms)
  // ══════════════════════════════════════════════════
  { id: 'invalidite-totale', term: 'Invalidite totale', definition: "Etat d'incapacite complete a exercer son emploi habituel (definition propre occupation, 2 premieres annees) ou toute occupation remuneratrice (apres 2 ans). Definitions variables selon les contrats.", category: 'invalidite_maladie', relatedTerms: ['invalidite-partielle', 'invalidite-longue-duree'], manual: 'F-312' },
  { id: 'invalidite-partielle', term: 'Invalidite partielle', definition: "Capacite reduite de travailler (ex: temps partiel). Certains contrats versent une prestation proportionnelle. Pas toujours couverte — verifier les conditions du contrat.", category: 'invalidite_maladie', relatedTerms: ['invalidite-totale', 'invalidite-longue-duree'], manual: 'F-312' },
  { id: 'invalidite-courte-duree', term: 'Invalidite de courte duree (ICD)', definition: "Couverture pour les premieres semaines/mois d'invalidite (generalement 17-26 semaines). Souvent offerte en assurance collective. Fait le pont avant l'invalidite de longue duree.", category: 'invalidite_maladie', relatedTerms: ['invalidite-longue-duree', 'periode-attente'], manual: 'F-312' },
  { id: 'invalidite-longue-duree', term: 'Invalidite de longue duree (ILD)', definition: "Couverture apres l'expiration de l'ICD. Peut durer jusqu'a 65 ans. Prestation typique: 60-70% du salaire brut. Definition change souvent de 'propre occupation' a 'toute occupation' apres 2 ans.", category: 'invalidite_maladie', relatedTerms: ['invalidite-courte-duree', 'invalidite-totale'], manual: 'F-312' },
  { id: 'maladie-grave', term: 'Maladie grave (assurance)', definition: "Assurance versant un montant forfaitaire au diagnostic d'une maladie grave couverte (cancer, crise cardiaque, AVC). Generalement 25-30 maladies couvertes. Delai de survie: 30 jours.", category: 'invalidite_maladie', relatedTerms: ['invalidite-totale', 'soins-longue-duree'], manual: 'F-312' },
  { id: 'soins-longue-duree', term: 'Soins de longue duree (assurance)', definition: "Assurance couvrant les frais de soins lorsqu'une personne ne peut plus accomplir les activites de la vie quotidienne (AVQ). Critere: incapacite a 2-3 AVQ sur 6 (se laver, s'habiller, manger, etc.).", category: 'invalidite_maladie', relatedTerms: ['maladie-grave', 'invalidite-longue-duree'], manual: 'F-312' },

  // ══════════════════════════════════════════════════
  // FONDS DISTINCTS (~12 terms)
  // ══════════════════════════════════════════════════
  { id: 'fonds-distincts-terme', term: 'Fonds distincts', definition: "Fonds de placement offerts exclusivement par les assureurs. Garantie de capital (75% ou 100%) a l'echeance ou au deces. Protection contre les creanciers. Designation de beneficiaire possible. Contrat individuel variable (CIV).", category: 'fonds_distincts', relatedTerms: ['garantie-echeance', 'garantie-deces', 'protection-creanciers'], manual: 'F-313' },
  { id: 'garantie-echeance', term: "Garantie a l'echeance", definition: "Garantie que le detenteur recevra au minimum 75% ou 100% des depots a la date d'echeance du contrat (generalement 10 ans). Protege contre les pertes du marche a long terme.", category: 'fonds_distincts', relatedTerms: ['garantie-deces', 'reinitialisation', 'fonds-distincts-terme'], manual: 'F-313' },
  { id: 'garantie-deces', term: 'Garantie au deces', definition: "Garantie que le beneficiaire recevra au minimum 75% ou 100% des depots au deces du rentier. Peut etre superieure a la valeur marchande si les marches ont baisse.", category: 'fonds_distincts', relatedTerms: ['garantie-echeance', 'fonds-distincts-terme'], manual: 'F-313' },
  { id: 'reinitialisation', term: 'Reinitialisation (reset)', definition: "Option permettant de fixer un nouveau montant garanti lorsque la valeur marchande depasse la garantie actuelle. Recommence la periode de garantie (10 ans). Peut etre automatique ou manuelle.", category: 'fonds_distincts', relatedTerms: ['garantie-echeance', 'garantie-deces'], manual: 'F-313' },
  { id: 'protection-creanciers', term: 'Protection contre les creanciers', definition: "Les fonds distincts avec beneficiaire designe (conjoint, enfant, parent, descendant) sont protégés contre les creanciers du deposant. Avantage majeur par rapport aux FCP.", category: 'fonds_distincts', relatedTerms: ['fonds-distincts-terme', 'insaisissabilite', 'beneficiaire-designe'], manual: 'F-313' },
  { id: 'rfg', term: 'RFG (Ratio des frais de gestion)', definition: "Pourcentage annuel preleve sur l'actif du fonds pour couvrir les frais de gestion, d'administration et la garantie. Les fonds distincts ont un RFG plus eleve que les FCP en raison des garanties.", category: 'fonds_distincts', relatedTerms: ['fonds-distincts-terme', 'dsr'], manual: 'F-313' },

  // ══════════════════════════════════════════════════
  // ORGANISMES (~12 terms)
  // ══════════════════════════════════════════════════
  { id: 'amf', term: 'AMF', definition: "Autorite des marches financiers. Organisme de reglementation du secteur financier au Quebec. Delivre les permis, surveille la conformite, recoit les plaintes, impose des sanctions.", category: 'organismes', relatedTerms: ['csf-org', 'chad-org'], manual: 'F-111', legalReference: "Loi sur l'AMF, RLRQ c. A-33.2" },
  { id: 'csf-org', term: 'CSF', definition: "Chambre de la securite financiere. Encadre les representants en assurance de personnes, planification financiere et courtage en epargne collective. Veille au respect de la deontologie.", category: 'organismes', relatedTerms: ['amf', 'syndic', 'comite-discipline'], manual: 'F-111' },
  { id: 'chad-org', term: 'CHAD', definition: "Chambre de l'assurance de dommages. Encadre les agents et courtiers en assurance de dommages et les experts en sinistres au Quebec.", category: 'organismes', relatedTerms: ['amf', 'csf-org'], manual: 'F-111' },
  { id: 'assuris-org', term: 'Assuris', definition: "Organisme de protection des souscripteurs d'assurance de personnes au Canada. Si un assureur membre fait faillite, Assuris garantit les polices (jusqu'a certains montants).", category: 'organismes', relatedTerms: ['pacicc-org'], manual: 'F-313' },
  { id: 'pacicc-org', term: 'PACICC / SIMA', definition: "Societe d'indemnisation en matiere d'assurances IARD. Protege les titulaires de polices d'assurance dommages si un assureur membre devient insolvable.", category: 'organismes', relatedTerms: ['assuris-org'], manual: 'MULTI' },
  { id: 'accap-org', term: 'ACCAP / CLHIA', definition: "Association canadienne des compagnies d'assurances de personnes. Association de l'industrie representant les assureurs vie/sante. Emet des lignes directrices (LD2, LD7, LD10).", category: 'organismes', relatedTerms: ['bac-org'], manual: 'MULTI' },
  { id: 'bac-org', term: 'BAC / IBC', definition: "Bureau d'assurance du Canada. Association nationale representant les assureurs IARD (auto, habitation, entreprise). Information aux consommateurs et plaidoyer.", category: 'organismes', relatedTerms: ['accap-org'], manual: 'MULTI' },
  { id: 'bsif-org', term: 'BSIF / OSFI', definition: "Bureau du surintendant des institutions financieres. Regulateur federal prudentiel des assureurs constitues au federal. Fixe les normes de capital et solvabilite (LICAT).", category: 'organismes', relatedTerms: ['amf', 'canafe'], manual: 'MULTI' },

  // ══════════════════════════════════════════════════
  // GENERAL (~10 terms)
  // ══════════════════════════════════════════════════
  { id: 'sinistre', term: 'Sinistre', definition: "Evenement dommageable couvert par le contrat donnant lieu a une reclamation. En assurance de personnes: deces, invalidite, maladie grave. L'assure doit declarer le sinistre dans les delais prevus.", category: 'general', relatedTerms: ['indemnite', 'reclamation', 'exclusion'], manual: 'MULTI', legalReference: 'Code civil du Quebec, art. 2470-2474' },
  { id: 'indemnite', term: 'Indemnite', definition: "Compensation financiere versee par l'assureur. En assurance de personnes, c'est un montant convenu (capital deces, rente). En assurance de dommages, c'est le montant de la perte reelle.", category: 'general', relatedTerms: ['sinistre', 'franchise', 'prestation'], manual: 'MULTI', legalReference: 'Code civil du Quebec, art. 2463' },
  { id: 'franchise', term: 'Franchise', definition: "Montant a la charge de l'assure avant que l'assureur commence a indemniser. Plus la franchise est elevee, plus la prime est basse. Courante en assurance de dommages, rare en assurance vie.", category: 'general', relatedTerms: ['prime', 'indemnite'], manual: 'MULTI' },
  { id: 'reassurance', term: 'Reassurance', definition: "Mecanisme par lequel un assureur transfere une partie de ses risques a un reassureur. Permet d'augmenter la capacite de souscription et de stabiliser les resultats. Types: proportionnelle et non proportionnelle.", category: 'general', relatedTerms: ['tarification', 'pool-risques'], manual: 'MULTI' },
  { id: 'loi-25', term: 'Loi 25 (Protection renseignements personnels)', definition: "Loi modernisant la protection des renseignements personnels au Quebec. Impose des obligations strictes de consentement, transparence et securite. Affecte la collecte d'informations en assurance.", category: 'general', relatedTerms: ['secret-professionnel', 'kyc'], manual: 'F-111' },
  { id: 'ufc', term: 'UFC (Unites de formation continue)', definition: "Exigence de perfectionnement professionnel obligatoire au Quebec: 30 UFC par cycle de 2 ans. Certaines UFC sont obligatoires en conformite et deontologie. Maintien du droit de pratique.", category: 'general', relatedTerms: ['amf', 'representant'], manual: 'F-111', legalReference: 'Reglement sur la formation continue, RLRQ c. D-9.2, r. 11' },
];

/** Search the glossary by query string (term or definition) */
export function searchGlossary(query: string): PqapGlossaryTerm[] {
  const lower = query.toLowerCase();
  return PQAP_GLOSSARY.filter(t =>
    t.term.toLowerCase().includes(lower) ||
    t.definition.toLowerCase().includes(lower) ||
    t.id.includes(lower)
  ).slice(0, 20);
}

/** Get all terms in a given category */
export function getTermsByCategory(category: GlossaryCategory): PqapGlossaryTerm[] {
  return PQAP_GLOSSARY.filter(t => t.category === category);
}

/** Get all terms from a given manual */
export function getTermsByManual(manual: GlossaryManual): PqapGlossaryTerm[] {
  return PQAP_GLOSSARY.filter(t => t.manual === manual || t.manual === 'MULTI');
}

/** Get a single term by ID */
export function getTermById(id: string): PqapGlossaryTerm | undefined {
  return PQAP_GLOSSARY.find(t => t.id === id);
}
