#!/usr/bin/env python3
"""
Generate SQL seed statements for PQAP exam questions → QuestionBank.
Creates QuestionBank entries and QuestionBankItem records from extracted JSON.

Usage: python3 scripts/generate-questions-seed.py > scripts/pqap-questions-seed.sql
Then apply: psql $DATABASE_URL < scripts/pqap-questions-seed.sql
"""
import json
import sys
import os
import uuid

def escape_sql(text: str) -> str:
    return text.replace("'", "''").replace("\\", "\\\\")

def escape_json(obj) -> str:
    return escape_sql(json.dumps(obj, ensure_ascii=False))

def main():
    script_dir = os.path.dirname(__file__)
    docx_path = os.path.join(script_dir, 'exam-questions-extracted.json')
    pdf_path = os.path.join(script_dir, 'exam-questions-pdf-extracted.json')

    all_sections = {}
    if os.path.exists(docx_path):
        with open(docx_path, 'r', encoding='utf-8') as f:
            all_sections.update(json.load(f))
    if os.path.exists(pdf_path):
        with open(pdf_path, 'r', encoding='utf-8') as f:
            all_sections.update(json.load(f))

    if not all_sections:
        print("ERROR: No question files found", file=sys.stderr)
        sys.exit(1)

    print("-- PQAP Exam Questions Seed")
    print("-- Generated by generate-questions-seed.py")
    print("-- Creates QuestionBank + QuestionBankItem records")
    print("-- Requires: an active tenant ID (uses first active tenant)")
    print()
    print("DO $$")
    print("DECLARE")
    print("  v_tenant_id TEXT;")
    print("  v_bank_id TEXT;")
    print("BEGIN")
    print("  SELECT id INTO v_tenant_id FROM \"Tenant\" WHERE status = 'ACTIVE' LIMIT 1;")
    print("  IF v_tenant_id IS NULL THEN")
    print("    RAISE EXCEPTION 'No active tenant found';")
    print("  END IF;")
    print()

    total_questions = 0
    total_banks = 0

    for section_key, section in all_sections.items():
        manual = section.get('manual', 'Unknown')
        source = section.get('source', section_key)
        questions = section.get('questions', [])
        if not questions:
            continue

        bank_id = f'qb-{section_key}-{uuid.uuid4().hex[:8]}'
        bank_name = f"PQAP {manual} — {source}"
        total_banks += 1

        print(f"  -- QuestionBank: {bank_name} ({len(questions)} questions)")
        print(f"  v_bank_id := '{bank_id}';")
        print(f"  INSERT INTO \"QuestionBank\" (id, \"tenantId\", name, description, category, \"questionCount\", \"createdAt\", \"updatedAt\")")
        print(f"  VALUES (v_bank_id, v_tenant_id, '{escape_sql(bank_name)}', 'Questions d''examen PQAP extraites de {escape_sql(source)}', '{escape_sql(manual)}', {len(questions)}, NOW(), NOW())")
        print(f"  ON CONFLICT DO NOTHING;")
        print()

        for i, q in enumerate(questions):
            item_id = f'qbi-{section_key}-{i:04d}'
            question_text = escape_sql(q.get('question', ''))
            q_type = q.get('type', 'MULTIPLE_CHOICE')
            options = q.get('options', [])

            # Build options JSON
            options_json = []
            for j, opt_text in enumerate(options):
                options_json.append({
                    'id': f'opt-{j}',
                    'text': opt_text,
                    'isCorrect': j == 0  # First option marked as correct by default (needs manual review)
                })

            print(f"  INSERT INTO \"QuestionBankItem\" (id, \"tenantId\", \"bankId\", type, question, options, \"sortOrder\", \"createdAt\", \"updatedAt\")")
            print(f"  VALUES ('{item_id}', v_tenant_id, v_bank_id, '{q_type}', '{question_text}', '{escape_json(options_json)}'::jsonb, {i}, NOW(), NOW())")
            print(f"  ON CONFLICT DO NOTHING;")

            total_questions += 1

        print()

    print("END $$;")
    print()
    print(f"-- Total: {total_banks} question banks, {total_questions} questions")

if __name__ == "__main__":
    main()
