#!/usr/bin/env python3
"""
Generate SQL seed statements for PQAP course content.
Maps extracted manual chapters to lesson manualText fields.

Usage: python3 scripts/generate-pqap-seed.py > scripts/pqap-content-seed.sql
Then apply: psql $DATABASE_URL < scripts/pqap-content-seed.sql
"""
import json
import sys
import os

def escape_sql(text: str) -> str:
    """Escape text for SQL string literal."""
    return text.replace("'", "''").replace("\\", "\\\\")

def main():
    content_path = os.path.join(os.path.dirname(__file__), 'pqap-manual-content.json')
    if not os.path.exists(content_path):
        print("ERROR: Run extract-pqap-content.py first", file=sys.stderr)
        sys.exit(1)

    with open(content_path, 'r', encoding='utf-8') as f:
        content = json.load(f)

    print("-- PQAP Manual Content Seed")
    print("-- Generated by generate-pqap-seed.py")
    print("-- Maps chapter content to lesson manualText fields")
    print("-- Requires existing courses with matching slug patterns")
    print()
    print("BEGIN;")
    print()

    manual_course_map = {
        'F-111': 'deontologie',
        'F-312': 'accident-maladie',
        'F-311': 'assurance-vie',
        'F-313': 'fonds-distincts',
    }

    for manual_id, manual in content.items():
        slug_pattern = manual_course_map.get(manual_id)
        if not slug_pattern:
            continue

        print(f"-- {manual_id}: {manual['title']}")
        print(f"-- Chapters: {len(manual['chapters'])}")
        print()

        for chap_num, chap_text in sorted(manual['chapters'].items(), key=lambda x: int(x[0])):
            escaped_text = escape_sql(chap_text)
            # Update the first lesson in the Nth chapter of the matching course
            print(f"-- Chapter {chap_num}")
            print(f"""UPDATE "Lesson" SET "manualText" = '{escaped_text}'
WHERE id = (
  SELECT l.id FROM "Lesson" l
  JOIN "CourseChapter" ch ON l."chapterId" = ch.id
  JOIN "Course" c ON ch."courseId" = c.id
  WHERE c.slug LIKE '%{slug_pattern}%'
  AND ch."sortOrder" = {int(chap_num) - 1}
  ORDER BY l."sortOrder" ASC
  LIMIT 1
);""")
            print()

    print("COMMIT;")
    print()
    print(f"-- Total: {sum(len(m['chapters']) for m in content.values())} chapters across {len(content)} manuals")

if __name__ == "__main__":
    main()
